### ISSUE TITLE
Laundry Pool Visual bug

### ISSUE THREAD

**Issue by TheTrueShadow** [HarbourMasters/2ship2harkinian#509] opened 2024-05-27 02:48 UTC
- [ ] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [ ] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:

See through in the laundry pool where rupees is is completely white
### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [X] Yes, here are the steps to reproduce the bug:

You should be able to see through 
### Screenshots or videos:

![image](https://github.com/HarbourMasters/2ship2harkinian/assets/80232013/68b6fbc1-120f-4b50-a442-683f8acd76a2)

### System Information:
- OS: Win 11
- GFX Backend:  DirectX
- Game Version: 1.0.0.0
- Rom Version:1.0

### Additional Information:

The other side works just fine as this image below shows 
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/80232013/be74eab3-f59f-4b82-8d1e-487b32bd3ffa)

**Comment by garrettjoecox** [comment] 2024-05-27 02:50
Thanks for the report! Closing as duplicate of #355

**Closed as not planned by garrettjoecox** 2024-05-27 02:50 UTC
Labels: bug
