### ISSUE TITLE
[Bug] Clock not freezing in some circumstances if time speed is set to zero

### ISSUE THREAD

**Issue by TheTrueShadow** [HarbourMasters/2ship2harkinian#632] opened 2024-06-01 05:24 UTC
- [X] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [X] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:

Time speed set to zero in some areas like some testing areas makes the time go backwards
### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [X] Yes, here are the steps to reproduce the bug:

### Expected behavior:

The clock to freeze and the time to not move backwards
### Screenshots or videos:

https://github.com/HarbourMasters/2ship2harkinian/assets/80232013/69b2641a-e007-447b-b0b3-aff512048b03

https://github.com/HarbourMasters/2ship2harkinian/assets/80232013/aad2593f-e1fe-4f52-9de5-29398269b116

### System Information:
- OS: Windows 11
- GFX Backend: DirectX
- Game Version:1.0.1
- Rom Version:1.0

### Additional Information:

on the 3rd day it seems to cycle through all the days (The Music is because of the scene)

**Comment by Archez** [comment] 2024-09-24 01:38
Hi @TheTrueShadow, looking into this and unfortunately the videos you have attached do not seem to be loading correctly.

Could you list reproduction steps and explain what "some testing areas" means? I have not been able to find a situation where this is happening, but I may be overlooking an edge case.

**Comment by TheTrueShadow** [comment] 2024-09-24 01:40
I will reupload them to YouTube and post links here if that's okay I think they should provide what I am experiencing

**Comment by TheTrueShadow** [comment] 2024-09-24 01:40
I will reupload them to YouTube and post links here if that's okay I think they should provide what I am experiencing

**Comment by TheTrueShadow** [comment] 2024-09-24 01:51
https://youtu.be/wOziOBsOyKQ 
https://youtu.be/MT5eULoGcfg 

So the testing areas are like either cut content is or an area that is solely used in the development in the game so I am assuming based on the scene layout I am assuming they just used it to test things like music based events or something like that. but this is the only area I found this bug in but I haven't really checked in a while.

**Comment by Archez** [comment] 2024-09-24 02:14
Could you explain how you got to those areas in the first place?
Did you ever experience this in regular gameplay, or only when messing with debug warping?

**Comment by TheTrueShadow** [comment] 2024-09-24 02:40
Oh yeah I thought that was in my video sorry yeah it's through debug warping it's by changing the scene too so it's unlikely to happen during normal gameplay.

**Comment by TheTrueShadow** [comment] 2024-09-24 02:43
It's actually in the video with the moon crash on how it works sorry if it's a little fast for it but how you do it. (Edit) Then you watch the one with the moon crash and that should be the correct order and shows how I used the debug menu and other stuff to show off what happened

**Comment by Archez** [comment] 2024-09-25 14:57
Ok I see, so in this case you are loading into a End Credits cutscene, and after some time the cutscene stops, giving you control of link in that map.

What normally happens when completing the game is that any time speed offsets are erased before the End Credits play. So if you had Inverted Song of Time active, it would change back to "normal" speed.
(Some maps have a default "normal" speed of 3, and others are 1 or 0. In the case of the End Credits, those are 0 which is why you see backwards time with the slider set to "freeze" which means -3)

The behavior you show above can be replicated by just playing Inverted Song of Time, then warping to the same location, as that also applies a similar time speed offset. This is because you are bypassing the original games check for changing the time speed.

Since this behavior is not related to the Save Editor specifically, and both Debug Warping and Save Editor are developer tools, I am going to close this issue in favor of not being a bug that was introduced by us.

If you happen to find a situation where this happens through just regular gameplay alone, then feel free to re-open this issue with exact reproduction steps.

**Closed as not planned by Archez** 2024-09-25 14:57 UTC
Labels: bug
