### ISSUE TITLE
Bombers password cutscene doesn't have the correct camera angle

### ISSUE THREAD

**Issue by pedrovay2003** [HarbourMasters/2ship2harkinian#654] opened 2024-06-03 19:01 UTC
- [X] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [X] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
When completing the Bombers minigame to get the password for their hideout, the cutscene doesn't show the Bombers members turning around with their numbers shown on their backs. The camera stays facing Link, and you only know that the password reveal is complete when a text box pops up.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [X] Yes, here are the steps to reproduce the bug:

### Expected behavior:
The camera should be aimed at the Bombers as they reveal the password

### System Information:
- OS: Windows
- GFX Backend: DirectX
- Game Version: 1.0.1
- Rom Version: NTSC GameCube

### Additional Information:
Resolution: 3840x2160 16:9 widescreen

**Comment by garrettjoecox** [comment] 2024-06-03 21:06
Thanks for the report! This has been known about for a bit but I guess we forgot to make a github issue!

**Comment by sitton76** [comment] 2024-06-03 21:49
I actually did make a issue on #330. Probably missed it because I did not use the word "Bomber" in the title.

That said I was under the assumption this only triggered on the Linux build, as I have not seen anyone else report it until now. So good to know that is not the case.

**Comment by briaguya0** [comment] 2024-06-04 00:24
i'm going to close this as a dupe of 330, thanks for the report!

**Closed as not planned by briaguya0** 2024-06-04 00:24 UTC
Labels: bug
