### ISSUE TITLE
The map in dungeons is not really good.

### ISSUE THREAD

**Issue by m9henri** [HarbourMasters/2ship2harkinian#634] opened 2024-06-01 17:19 UTC
- [ ] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [ ] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
The map in dungeons is not really good.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug

### Expected behavior:
The blue square should be filling out only the room and not the whole square.

### Screenshots or videos:
![Screenshot 2024-06-01 191245](https://github.com/HarbourMasters/2ship2harkinian/assets/97912678/41401829-5729-4b8b-ac2f-4218c5f348f7)

### System Information:
- OS: Windows 11
- GFX Backend: DirectX
- Game Version: 1.1
- Rom Version: 1.0 USA

**Comment by Archez** [comment] 2024-06-02 05:04
Thank you for the report. We already have an issue tracking the pause dungeon maps here https://github.com/HarbourMasters/2ship2harkinian/issues/409
I've added your image to it as an example of how it looks now. I'll be closing this now as a duplicate of it.

**Closed as not planned by Archez** 2024-06-02 05:04 UTC
Labels: bug
