### ISSUE TITLE
Xbox One Controller Resets Custom Inputs (+ inputs a set of new ones?) if the bluetooth self disconnects due to inactivity from Computer

### ISSUE THREAD

**Issue by Ash-Hybrid** [HarbourMasters/2ship2harkinian#582] opened 2024-05-28 14:50 UTC
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
I left my Bluetooth Connected Xbox One controller alone to go do something and when i came back to it, it had disconnected, when i turned it back on and resumed playing, I tried moving my camera around (as I had Free-Look enabled) and ended up using my Bombs, when I threw them, i felt my controller rumble (even though i had it turned off). When i checked the Controller Input Menu, it showed there was another set of Xbox Inputs but they were Red. In addition, rumble was on again.

### Can you reproduce? If so please list the steps:
- [x] No, I cannot reproduce this bug
- [ ] Yes, here are the steps to reproduce the bug:
1. Connect Xbox One Controller via Bluetooth, Launch Program, & Begin Playing
2. Customize Inputs, Leave Controller & Game Idle (preferably on the pause menu), Once Controller Disconnects, Reconnect and Resume Play 
3. Witness (or use Free-Cam and nearly blow yourself up as i did.).

### System Information:
- OS: Windows 10
- GFX Backend: DirectX11
- Game Version: Rika-Alfa 1.0.0
- Rom Version: "MM-US 1.0"

### Additional Information:
I am unable to reproduce this bug manually or organically. I tried to do it manually at first and it didnt do anything, stayed as is, but when i did it the way it happened before, it also didnt do it either. Im leaving the steps there as a means to possibly replicate this one in a million chance of a bug. At first i thought it was because the program thought i was using a new controller, despite using the same controller (hence why it probably inputted an additional set of xbox inputs).

**Comment by FilGoodInc** [comment] 2024-05-28 17:58
Had the same problem.

- You can reproduce the bug by removing the battery from the controller.
- Controller Auto Shutdowns after a while. When reconnecting the buttons are back to default inputs for Xbox controller.
- Old Input Mapping are still present but they Say Xbox Series X Controller (Disconnected) and default to generic button naming scheme (ie. B0 instead of A, B9 instead of LB)
- In the Device Tab there's 3 Devices (I only have 1 controller that I connected 1 at the start and reconnected 2 times)
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/23322177/5da6e92c-6e29-4ca1-9011-98c8f933513c)
- Mappings stay in the list they are just to a controller the program thinks is disconnected:
(Red here is the correct mappings I modified, other 2 colors appeared after reconnect)
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/23322177/4855b30e-89b2-4fc3-b65e-2144c6dfb917)

**Comment by Pheener** [comment] 2024-05-29 02:03
Running into the same issue as above. When controller disconnects due to inactivity and powers back on, Ship2 treats it like a brand new controller, and often resets the inputs to inoperable dummy "axis" controls, rather than what I assume would normally be xinput.  Controls must be fully reset every time.

![image](https://github.com/HarbourMasters/2ship2harkinian/assets/128332227/b38dfa75-b841-4732-b60b-06ed8a7312bc)
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/128332227/fcd5bef2-bcd5-43eb-b793-91a9110aea39)

**Comment by briaguya0** [comment] 2024-06-04 00:54
this should be fixed in Rika Bravo (1.0.1), if this is still an issue on that version (after clearing out all the mappings from `2ship2harkinian.json`) i can reopen this

**Closed as completed by briaguya0** 2024-06-04 00:54 UTC
Labels: bug, input
