### ISSUE TITLE
Enhancement "Skip Intro Sequence" Overwrites save files on reload

### ISSUE THREAD

**Issue by VideoGameRoulette** [HarbourMasters/2ship2harkinian#560] opened 2024-05-28 01:55 UTC
- [✓ ] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [✓ ] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
When Enhancement "Skip Intro Sequence" is enabled, any save loaded gets overwritten to the base state or the enhancement.
Meaning all progress made and saved gets replaced and you start back outside clocktown as deku link.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [✓ ] Yes, here are the steps to reproduce the bug:
1. Go to Enhancement enable "Skip Intro Sequence"
2. Complete some tasks get some items and save either using the pause menu save feature or owls.
3. Close game
4. Start Game
5. Load save file
6. Now all progress has been reset to default save state of "Skip Intro Sequence"

### Expected behavior:
1. Go to Enhancement enable "Skip Intro Sequence"
2. Complete some tasks get some items and save either using the pause menu save feature or owls.
3. Close game
4. Start Game
5. Load save file
6. All progress should continue where you left off if not a fresh save file.
6b. If fresh save file then it should skip the intro.

### System Information:
- OS: Windows 10
- GFX Backend: DirectX
- Game Version: 1.0.0
- Rom Version: Legend of Zelda, The - Majora's Mask (USA).z64

### Additional Information:
Instead of re-writing the save files on load, it run a sub-routine to write the skip when you create the new file if the feature is enabled? might be less prone to issues if you do it that way compared to its current flow this way you don't have to do any comparison checks on the save to see if its a fresh save or a save with lots progress and it prevents saves from being overwritten by mistake.

**Comment by garrettjoecox** [comment] 2024-05-28 02:10
I was unable to reproduce this with the reproduction steps, any ideas if you missed anything?

**Comment by VideoGameRoulette** [comment] 2024-05-28 23:17
It could also be skip story cutscene I'm going to record some footage tonight to showcase the issue

**Comment by VideoGameRoulette** [comment] 2024-05-29 00:43
[https://www.youtube.com/watch?v=VRl94vJiDtE](https://www.youtube.com/watch?v=VRl94vJiDtE)

**Comment by garrettjoecox** [comment] 2024-05-29 00:52
What I'm observing in your video is vanilla behavior, I think maybe what you are hoping for is the "persistent owl saves" enhancement?

Pause saving and auto saving just create and re-use the owl saving functionality built into MM. Owl saves will not overwrite your previous "new cycle" save, and when you load into them without the aforementioned enhancement they will self destruct, if you then load into the save again, you will load your previous "new cycle save" losing any progress made.

**Comment by garrettjoecox** [comment] 2024-05-30 13:57
Going to close this, if you disagree with this conclusion feel free to re-open!

**Closed as completed by garrettjoecox** 2024-05-30 13:57 UTC
Labels: bug
