### ISSUE TITLE
Can't jam with Jabas

### ISSUE THREAD

**Issue by ElBuenTelle** [HarbourMasters/2ship2harkinian#741] opened 2024-07-10 01:12 UTC
https://github.com/HarbourMasters/2ship2harkinian/assets/36112986/ddabf9ef-86f9-4340-9f8c-2906f246609d

As soon he is finished playing the games things a played an incorrect note.

**Comment by Malkierian** [comment] 2024-07-10 01:19
Closing as duplicate of #680

**Closed as not planned by Malkierian** 2024-07-10 01:19 UTC
Labels: bug, duplicate
